#if !canImport(ObjectiveC)
import XCTest

extension JSONSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONSessionTests = [
        ("testCodable", testCodable),
        ("testData", testData),
        ("testJSON", testJSON),
        ("testString", testString),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONSessionTests.__allTests__JSONSessionTests),
    ]
}
#endif
